import Head from "next/head";
import CreatePost from "../components/CreatePost";
import CreatePostPartTwo from "../components/CreatePostPartTwo";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Posts from "../components/Posts";
import Stories from "../components/Stories";

export default function Home() {
  return (
    <div className="sm:grid place-content-center ">
      <Head>
        <title>My_Facebook </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/f.jpg" />
      </Head>
      <main className="sm:max-w-md">
        {/* header */}
        <Header />
        {/* createPost */}
        <CreatePost />
        {/* createpostpart2 */}
        <CreatePostPartTwo />
        {/* stories */}
        <Stories />
        {/* posts */}
        <Posts />
        {/* footer */}
        <Footer />
      </main>
    </div>
  );
}
